from os import system
import time, shutil
columns = shutil.get_terminal_size().columns

def Sit5():
    system("cls")
    print("13 November 2019 19:26")
    print("-" * (columns - 23))
    print("Home".center(columns-20))
    time.sleep(0.7)

    print("Mum:(knocked)\n\tIt's time for dinner.")
    time.sleep(2)
    print("\n(You walked out of your room and saw your father watching TVB again.)")
    time.sleep(1)
    print("(...)")
    time.sleep(1)
    print("\nFather:\n\tThe protesters are all controlled by conspiracies from the US!")
    time.sleep(2)
    print("\tRemember son, you are always Chinese! Do not betray China!\n")
    time.sleep(2)

    choice = ""
    while choice != "1" and choice != "2":
        choice = input("1. Refute   2. Pretend to be a patriot (1/2)")

    if choice == "1":
        print("\nYou:\n\tChinese? Who?")
        time.sleep(1.5)
        print("\tI am a Hongkonger!")
        time.sleep(1.5)
        print("\tI have no ethnic identity for a country with no democracy and full of lies!")
        time.sleep(2)
        print("\tThere's no such thing called betraying China since I am not Chinese!")
        time.sleep(2)
        print("\tI think I might even lead their way in when the U.S armies come!")
        time.sleep(3)
        print("\nFather:\n\tHow can you say that?")
        time.sleep(1.5)
        print("\tMy father was Chinese. I am Chinese and you are born Chinese!")
        time.sleep(2)
        print("\tI am so disappointed in you! You're selling you soul to make money!")
        time.sleep(2)
        print("\tI am cutting you off financially!")
        time.sleep(2.5)
        print("\nYou:\n\tYou serious? You think I cared?")
        time.sleep(2)
        print("\tI was not, am not and will never be a Chinese!")
        time.sleep(1)
        print("\nMum: (slammed the table)\n\tEnough! ")
        time.sleep(1.5)
        print("\tI just want a quiet dinner together!")
        time.sleep(2)
        print("(......)")
        system("pause")
        return True
    else:
        print("\nYou:\n\tToday's chaotic situations are the result of the struggle between")
        print("\tthe Princelings and the ShangHai Clique!")
        time.sleep(3)
        print("\n\tThey controlled the police to mess up Hong Kong and deliberately created")
        print("\ttroubles to our great president Xi!")
        time.sleep(3)
        print("\tDon't trust the Hong Kong government.")
        time.sleep(2)
        print("\tMost of their family members are holding foreign passports!")
        time.sleep(2)
        print("\tThey are the suspicious ones!")
        time.sleep(3)
        print("\nFather:\n\tStop pretending, son.")
        time.sleep(2)
        print("\tI know that you never liked China.")
        time.sleep(2)
        print("\nYou:\n\tYes, I never did! But I am trying to help you here, father!")
        time.sleep(2)
        print("\tNo one wants to sabotage Hong Kong, right?")
        time.sleep(2)
        print("\tThere is someone trying to benefit from this chaos.")
        time.sleep(2)
        print("\tThey are probably part of the pro-establishment camp of the Chinese government!")
        time.sleep(2)
        print("\tIf you really do love Hong Kong and your country,")
        time.sleep(1)
        print("\tNEVER TRUST THE HONG KONG GOVERNMENT AND THE POLICE!")

        time.sleep(2)
        print("\nFather:\n\t...")
        time.sleep(1)
        print("\tStill, you students should not throw gasoline bombs anyway...")
        time.sleep(2)
        print("\nMum:\n\tOkay Okay. Just eat quietly....")
        system("pause")
        return False